"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import type { StoreData,StoreProduct } from "../lib/store-data";

type CartLine={product:StoreProduct;qty:number;input:string};
type Profile={name:string;mobile:string};
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(n)+" تومان";
const digits=(s:string)=>s.replace(/\D/g,"").replace(/(.{4})/g,"$1 ").trim();

export default function Storefront({data}:{data:StoreData}){
 const {categories,products,settings}=data;
 const [query,setQuery]=useState(""),[category,setCategory]=useState("all"),[selected,setSelected]=useState<StoreProduct|null>(null),[qty,setQty]=useState(1),[input,setInput]=useState(""),[cart,setCart]=useState<CartLine[]>([]),[cartOpen,setCartOpen]=useState(false),[walletOpen,setWalletOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[supportOpen,setSupportOpen]=useState(false),[toast,setToast]=useState(""),[sort,setSort]=useState<"popular"|"low"|"high">("popular"),[profile,setProfile]=useState<Profile>({name:"",mobile:""}),[favorites,setFavorites]=useState<string[]>([]),[walletAmount,setWalletAmount]=useState(""),[checkoutDone,setCheckoutDone]=useState("");
 useEffect(()=>{try{const c=localStorage.getItem("persian-shop-cart");if(c)setCart(JSON.parse(c));const p=localStorage.getItem("persian-shop-profile");if(p)setProfile(JSON.parse(p));const f=localStorage.getItem("persian-shop-favs");if(f)setFavorites(JSON.parse(f));}catch{}},[]);
 useEffect(()=>{localStorage.setItem("persian-shop-cart",JSON.stringify(cart))},[cart]);
 useEffect(()=>{localStorage.setItem("persian-shop-favs",JSON.stringify(favorites))},[favorites]);
 const filtered=useMemo(()=>{let list=products.filter(p=>(category==="all"||p.category===category)&&(!query||`${p.name} ${p.en} ${p.description}`.toLowerCase().includes(query.toLowerCase())));if(sort==="low")list=[...list].sort((a,b)=>a.price-b.price);if(sort==="high")list=[...list].sort((a,b)=>b.price-a.price);return list},[products,category,query,sort]);
 const cartCount=cart.reduce((s,x)=>s+x.qty,0),cartTotal=cart.reduce((s,x)=>s+x.product.price*x.qty,0);
 const featured=products.slice(0,12),ai=products.filter(p=>p.category==="ai").slice(0,8),digital=products.filter(p=>p.category==="digital").slice(0,8),social=products.filter(p=>["instagram","telegram","tiktok","youtube"].includes(p.category)).slice(0,8);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),1800)};
 const openProduct=(p:StoreProduct)=>{setSelected(p);setQty(1);setInput("")};
 const add=(e?:FormEvent)=>{e?.preventDefault();if(!selected)return;setCart(v=>{const i=v.findIndex(x=>x.product.slug===selected.slug&&x.input===input);if(i<0)return [...v,{product:selected,qty,input}];const copy=[...v];copy[i]={...copy[i],qty:copy[i].qty+qty};return copy});setSelected(null);notify("محصول به سبد خرید اضافه شد")};
 const toggleFav=(slug:string)=>setFavorites(v=>v.includes(slug)?v.filter(x=>x!==slug):[...v,slug]);
 const selectCat=(id:string)=>{setCategory(id);setTimeout(()=>document.getElementById("products")?.scrollIntoView({behavior:"smooth"}),10)};
 const copy=async(text:string,label:string)=>{if(!text)return;await navigator.clipboard.writeText(text);notify(`${label} کپی شد`)};
 const saveProfile=(e:FormEvent)=>{e.preventDefault();localStorage.setItem("persian-shop-profile",JSON.stringify(profile));setAccountOpen(false);notify("اطلاعات حساب ذخیره شد")};
 const finishCheckout=()=>{if(!cart.length)return;const ref=`PS-${Date.now().toString().slice(-8)}`;setCheckoutDone(ref);setCart([]);notify("سفارش در سایت ثبت شد")};
 return <main className="shop">
  <div className="promoBar">⚡ خرید سریع سرویس‌های دیجیتال با پشتیبانی Persian Shop <button onClick={()=>setWalletOpen(true)}>افزایش موجودی کیف پول</button></div>
  <header className="header">
   <div className="container headerMain">
    <button className="logo" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><span className="logoMark">P</span><span><b>{settings.shopName}</b><small>Digital Marketplace</small></span></button>
    <label className="searchBox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>document.getElementById("products")?.scrollIntoView({behavior:"smooth"})} placeholder="جستجو در Persian Shop..."/>{query&&<button onClick={()=>setQuery("")}>×</button>}</label>
    <div className="headActions"><button onClick={()=>setAccountOpen(true)}>👤 <span>{profile.name||"ورود | ثبت‌نام"}</span></button><i/><button onClick={()=>setCartOpen(true)} className="cartIcon">🛒{cartCount>0&&<b>{cartCount}</b>}</button></div>
   </div>
   <div className="container navRow"><button className="mega" onClick={()=>selectCat("all")}>☰ دسته‌بندی محصولات</button>{categories.slice(0,5).map(c=><button key={c.id} onClick={()=>selectCat(c.id)}>{c.emoji} {c.name}</button>)}<span className="navSpacer"/><button onClick={()=>setWalletOpen(true)}>💳 کیف پول</button><button onClick={()=>setSupportOpen(true)}>🎧 پشتیبانی</button></div>
  </header>

  <div className="container stories">{categories.map(c=><button key={c.id} onClick={()=>selectCat(c.id)}><span>{c.emoji}</span><b>{c.name}</b><small>{c.count} محصول</small></button>)}<button onClick={()=>setSupportOpen(true)}><span>🎧</span><b>پشتیبانی</b><small>پاسخگویی سریع</small></button></div>

  <section className="container heroShop">
   <div className="heroCopy"><span>فروشگاه آنلاین Persian Shop</span><h1>خرید سرویس‌های دیجیتال<br/><mark>سریع، ساده و مطمئن</mark></h1><p>محصولات شبکه‌های اجتماعی، اشتراک‌های هوش مصنوعی و سرویس‌های پرمیوم در یک فروشگاه کامل.</p><div><button onClick={()=>selectCat("all")} className="yellowBtn">مشاهده همه محصولات</button><button onClick={()=>setWalletOpen(true)} className="whiteBtn">شارژ کیف پول</button></div><ul><li>✓ بدون دریافت رمز عبور</li><li>✓ قیمت به‌روز از مدیریت</li><li>✓ پشتیبانی سفارش</li></ul></div>
   <div className="heroVisual"><div className="heroBadge">🔥 پیشنهاد امروز</div><div className="stackCard c1">🤖<b>AI Premium</b></div><div className="stackCard c2">📸<b>Social Growth</b></div><div className="stackCard c3">💎<b>Digital Premium</b></div><div className="heroCoin">P</div></div>
  </section>

  <section className="container amazing"><div className="amazingIntro"><span>⚡</span><h2>پیشنهاد ویژه</h2><p>محصولات منتخب فروشگاه</p><button onClick={()=>selectCat("all")}>مشاهده همه ←</button></div><div className="amazingScroll">{featured.map((p,i)=><ProductCard key={p.slug} p={p} onOpen={openProduct} onFav={toggleFav} fav={favorites.includes(p.slug)} badge={i<4?`${10+i*5}%`:undefined}/>)}</div></section>

  <section className="container banners"><button onClick={()=>selectCat("ai")} className="banner aiBanner"><span>🤖</span><div><small>اشتراک ابزارهای هوش مصنوعی</small><b>AI Premium Collection</b><em>مشاهده محصولات ←</em></div></button><button onClick={()=>selectCat("digital")} className="banner digitalBanner"><span>💎</span><div><small>اشتراک‌های پرمیوم</small><b>Premium Accounts</b><em>خرید سریع ←</em></div></button></section>

  <CategoryStrip title="محبوب‌ترین سرویس‌های شبکه اجتماعی" products={social} onOpen={openProduct} onFav={toggleFav} favorites={favorites} onAll={()=>selectCat("instagram")}/>
  <CategoryStrip title="اشتراک‌های هوش مصنوعی" products={ai} onOpen={openProduct} onFav={toggleFav} favorites={favorites} onAll={()=>selectCat("ai")}/>
  <CategoryStrip title="محصولات دیجیتال و پرمیوم" products={digital} onOpen={openProduct} onFav={toggleFav} favorites={favorites} onAll={()=>selectCat("digital")}/>

  <section id="products" className="container productSection"><div className="productsTitle"><div><h2>{category==="all"?"همه محصولات":categories.find(c=>c.id===category)?.name}</h2><p>{filtered.length} محصول فعال</p></div><div className="sort"><span>☷ مرتب‌سازی:</span><button className={sort==="popular"?"on":""} onClick={()=>setSort("popular")}>پیشنهادی</button><button className={sort==="low"?"on":""} onClick={()=>setSort("low")}>ارزان‌ترین</button><button className={sort==="high"?"on":""} onClick={()=>setSort("high")}>گران‌ترین</button></div></div><div className="filterChips"><button className={category==="all"?"on":""} onClick={()=>setCategory("all")}>همه</button>{categories.map(c=><button key={c.id} className={category===c.id?"on":""} onClick={()=>setCategory(c.id)}>{c.emoji} {c.name}</button>)}</div>{filtered.length?<div className="gridProducts">{filtered.map(p=><ProductCard key={p.slug} p={p} onOpen={openProduct} onFav={toggleFav} fav={favorites.includes(p.slug)}/>)}</div>:<div className="noResult">محصولی با این جستجو پیدا نشد.<button onClick={()=>{setQuery("");setCategory("all")}}>پاک کردن فیلترها</button></div>}</section>

  <section className="container trust"><article>🚀<div><b>ثبت سفارش سریع</b><small>فرآیند ساده و شفاف خرید</small></div></article><article>🔐<div><b>بدون دریافت پسورد</b><small>حفظ امنیت اطلاعات حساب</small></div></article><article>💳<div><b>پرداخت انعطاف‌پذیر</b><small>کارت‌به‌کارت و USDT</small></div></article><article>🎧<div><b>پشتیبانی سفارش</b><small>پیگیری وضعیت خرید</small></div></article></section>

  <footer className="footer"><div className="container"><div className="footerBrand"><div className="logo"><span className="logoMark">P</span><span><b>{settings.shopName}</b><small>Premium Digital Marketplace</small></span></div><p>فروشگاه تخصصی خدمات دیجیتال، شبکه‌های اجتماعی و اشتراک‌های پرمیوم.</p></div><div><b>دسترسی سریع</b><button onClick={()=>selectCat("all")}>همه محصولات</button><button onClick={()=>setWalletOpen(true)}>کیف پول</button><button onClick={()=>setSupportOpen(true)}>پشتیبانی</button></div><div><b>دسته‌بندی‌ها</b>{categories.slice(0,4).map(c=><button key={c.id} onClick={()=>selectCat(c.id)}>{c.name}</button>)}</div><div><b>حساب کاربری</b><button onClick={()=>setAccountOpen(true)}>اطلاعات من</button><button onClick={()=>setCartOpen(true)}>سبد خرید</button><button onClick={()=>notify("لیست علاقه‌مندی‌ها در مرورگر شما ذخیره شده است")}>علاقه‌مندی‌ها ({favorites.length})</button></div></div><div className="container copyright">© 2026 Persian Shop — تمامی حقوق محفوظ است.</div></footer>

  {selected&&<div className="modalBack" onMouseDown={()=>setSelected(null)}><form className="productModal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><button type="button" className="x" onClick={()=>setSelected(null)}>×</button><div className="modalImage"><img src={selected.image} alt={selected.name}/><button type="button" className={favorites.includes(selected.slug)?"fav active":"fav"} onClick={()=>toggleFav(selected.slug)}>♡</button></div><div className="modalInfo"><small>{categories.find(c=>c.id===selected.category)?.name}</small><h2>{selected.name}</h2><div className="rating">★ ۴.۸ <span>• محصول فعال و قابل سفارش</span></div><p className="desc">{selected.description||"این محصول از کاتالوگ اصلی Persian Shop دریافت شده است."}</p><div className="featureList"><span>🛡 سفارش امن</span><span>⚡ شروع پردازش پس از ثبت</span><span>🔐 بدون نیاز به رمز عبور</span></div><label>اطلاعات لازم برای سفارش<small>{selected.inputPrompt}</small><textarea required value={input} onChange={e=>setInput(e.target.value)} placeholder="لینک، ایمیل یا اطلاعات خواسته‌شده را وارد کنید..."/></label><div className="buyBox"><div className="qty"><button type="button" onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button type="button" onClick={()=>setQty(qty+1)}>+</button></div><div className="price"><small>مبلغ نهایی</small><strong>{money(selected.price*qty)}</strong></div><button className="addCart" type="submit">افزودن به سبد خرید</button></div></div></form></div>}

  {cartOpen&&<><div className="drawerBack" onClick={()=>setCartOpen(false)}/><aside className="cartDrawer"><div className="drawerTitle"><h2>سبد خرید</h2><button onClick={()=>setCartOpen(false)}>×</button></div>{checkoutDone?<div className="checkoutDone"><span>✓</span><h3>درخواست سفارش ثبت شد</h3><p>کد پیگیری: <b>{checkoutDone}</b></p><small>برای تکمیل پرداخت از کیف پول یا پشتیبانی استفاده کنید.</small><button onClick={()=>{setCheckoutDone("");setCartOpen(false);setWalletOpen(true)}}>رفتن به کیف پول</button></div>:cart.length?<><div className="cartItems">{cart.map((x,i)=><article key={`${x.product.slug}-${i}`}><img src={x.product.image} alt=""/><div><b>{x.product.name}</b><small>{x.qty} × {money(x.product.price)}</small><em>{x.input}</em></div><button onClick={()=>setCart(v=>v.filter((_,n)=>n!==i))}>×</button></article>)}</div><div className="cartSummary"><div><span>تعداد کالا</span><b>{cartCount}</b></div><div><span>مبلغ قابل پرداخت</span><strong>{money(cartTotal)}</strong></div><button onClick={finishCheckout}>ثبت و ادامه سفارش</button></div></>:<div className="emptyCart">🛒<h3>سبد خرید شما خالی است</h3><p>از بین محصولات فروشگاه انتخاب کنید.</p><button onClick={()=>{setCartOpen(false);selectCat("all")}}>مشاهده محصولات</button></div>}</aside></>}

  {walletOpen&&<div className="modalBack" onMouseDown={()=>setWalletOpen(false)}><div className="walletModal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setWalletOpen(false)}>×</button><h2>💳 افزایش موجودی کیف پول</h2><p>مبلغ موردنظر را وارد کنید و روش پرداخت را انتخاب کنید.</p><label className="amountInput">مبلغ شارژ (تومان)<input inputMode="numeric" value={walletAmount} onChange={e=>setWalletAmount(e.target.value.replace(/\D/g,""))} placeholder="مثلاً 500000"/>{walletAmount&&<small>{money(Number(walletAmount))}</small>}</label><div className="paymentMethods">{settings.cardEnabled&&<article><div className="methodHead"><span>💳</span><div><b>کارت‌به‌کارت</b><small>تأیید توسط مدیریت</small></div></div><label>شماره کارت</label><button className="copyField" onClick={()=>copy(settings.cardNumber,"شماره کارت")}><b dir="ltr">{digits(settings.cardNumber)||"در مدیریت تنظیم نشده"}</b><span>کپی</span></button><p>به نام: {settings.cardHolder||"—"}</p>{settings.cardText&&<small className="paymentNote">{settings.cardText}</small>}</article>}{settings.cryptoEnabled&&<article><div className="methodHead"><span>₮</span><div><b>USDT</b><small>شبکه {settings.cryptoNetwork}</small></div></div><label>آدرس کیف پول</label><button className="copyField" onClick={()=>copy(settings.cryptoAddress,"آدرس کیف پول")}><b dir="ltr">{settings.cryptoAddress?`${settings.cryptoAddress.slice(0,10)}...${settings.cryptoAddress.slice(-8)}`:"در مدیریت تنظیم نشده"}</b><span>کپی</span></button>{settings.cryptoText&&<small className="paymentNote">{settings.cryptoText}</small>}</article>}</div><button className="receiptBtn" onClick={()=>{setWalletOpen(false);setSupportOpen(true)}}>پرداخت کردم؛ ارسال رسید به پشتیبانی</button></div></div>}

  {accountOpen&&<div className="modalBack" onMouseDown={()=>setAccountOpen(false)}><form className="accountModal" onSubmit={saveProfile} onMouseDown={e=>e.stopPropagation()}><button type="button" className="x" onClick={()=>setAccountOpen(false)}>×</button><span className="accountAvatar">👤</span><h2>حساب کاربری</h2><p>این اطلاعات روی همین دستگاه برای ساده‌تر شدن خرید ذخیره می‌شود.</p><label>نام و نام خانوادگی<input required value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="نام شما"/></label><label>شماره موبایل<input required inputMode="tel" value={profile.mobile} onChange={e=>setProfile({...profile,mobile:e.target.value})} placeholder="09xxxxxxxxx"/></label><button type="submit">ذخیره اطلاعات</button></form></div>}

  {supportOpen&&<div className="modalBack" onMouseDown={()=>setSupportOpen(false)}><div className="supportModal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setSupportOpen(false)}>×</button><span>🎧</span><h2>پشتیبانی Persian Shop</h2><p>برای پیگیری سفارش، ارسال رسید یا سوال درباره محصول از پشتیبانی استفاده کنید.</p>{settings.supportUsername?<a target="_blank" rel="noreferrer" href={`https://t.me/${settings.supportUsername.replace(/^@/,"")}`}>باز کردن پشتیبانی در تلگرام</a>:<button onClick={()=>notify("نام کاربری پشتیبانی هنوز در مدیریت تنظیم نشده")}>پشتیبانی تلگرام</button>}<small>نام کاربری: {settings.supportUsername||"در پنل مدیریت تنظیم نشده"}</small></div></div>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}

function ProductCard({p,onOpen,onFav,fav,badge}:{p:StoreProduct;onOpen:(p:StoreProduct)=>void;onFav:(s:string)=>void;fav:boolean;badge?:string}){return <article className="pCard"><div className="pImage"><img src={p.image} alt={p.name} loading="lazy"/>{badge&&<span className="discount">{badge}</span>}<button className={fav?"heart active":"heart"} onClick={()=>onFav(p.slug)}>♡</button></div><div className="pBody"><h3>{p.name}</h3><div className="pMeta"><span>★ ۴.۸</span><small>آماده سفارش</small></div><div className="pPrice"><strong>{money(p.price)}</strong></div><button className="pBuy" onClick={()=>onOpen(p)}>مشاهده و سفارش</button></div></article>}
function CategoryStrip({title,products,onOpen,onFav,favorites,onAll}:{title:string;products:StoreProduct[];onOpen:(p:StoreProduct)=>void;onFav:(s:string)=>void;favorites:string[];onAll:()=>void}){if(!products.length)return null;return <section className="container categoryStrip"><div className="stripHead"><h2>{title}</h2><button onClick={onAll}>مشاهده همه ←</button></div><div className="stripProducts">{products.map(p=><ProductCard key={p.slug} p={p} onOpen={onOpen} onFav={onFav} fav={favorites.includes(p.slug)}/>)}</div></section>}
