"use client";

import { FormEvent,useMemo,useState,type CSSProperties } from "react";
import { categories,featured,products,type CategoryId,type Product } from "../data/catalog";

type Lang="fa"|"en";
type CartLine={product:Product;qty:number;target:string};
const money=(n:number,l:Lang)=>new Intl.NumberFormat(l==="fa"?"fa-IR":"en-US").format(n)+(l==="fa"?" تومان":" Toman");
const text={
fa:{products:"محصولات",wallet:"کیف پول",support:"پشتیبانی",login:"ورود / حساب کاربری",badge:"فروشگاه دیجیتال Persian Shop",h1:"همه سرویس‌های دیجیتال، در یک فروشگاه حرفه‌ای",lead:"همان محصولات فروشگاه تلگرامی با دسته‌بندی دقیق، تصاویر اختصاصی و ثبت سفارش بدون دریافت رمز عبور.",browse:"مشاهده محصولات",topup:"افزایش موجودی",cats:"دسته‌بندی خدمات",featured:"محصولات پیشنهادی",all:"همه محصولات",search:"جستجو بین محصولات و سرویس‌ها...",order:"سفارش",cart:"سبد سفارش",empty:"سبد سفارش خالی است.",sum:"جمع",checkout:"ادامه ثبت سفارش",modal:"ثبت سفارش",qty:"تعداد بسته",target:"لینک عمومی / ایمیل یا نام کاربری",targetHint:"برای شبکه‌های اجتماعی فقط لینک عمومی؛ برای اشتراک‌ها ایمیل یا نام کاربری. رمز عبور ارسال نکنید.",add:"افزودن به سبد",cancel:"انصراف",added:"به سبد اضافه شد",walletTitle:"کیف پول و پرداخت",card:"کارت‌به‌کارت",cardDesc:"مبلغ شارژ → نمایش شماره کارت → ارسال رسید → تأیید مدیریت → افزایش موجودی",usdt:"USDT",usdtDesc:"محاسبه معادل تتر → ارسال رسید یا TXID → تأیید مدیریت",safe:"امن و بدون دریافت رمز",safeDesc:"اطلاعات حساس حساب دریافت نمی‌شود. سفارش‌ها با لینک عمومی یا شناسه حساب ثبت می‌شوند.",results:"نتیجه",footer:"Persian Shop — Premium Digital Marketplace"},
en:{products:"Products",wallet:"Wallet",support:"Support",login:"Login / Account",badge:"Persian Shop Digital Store",h1:"Premium digital services in one polished storefront",lead:"The same Telegram-store catalog with clean categories, dedicated artwork and password-free ordering.",browse:"Browse products",topup:"Top up wallet",cats:"Service categories",featured:"Featured products",all:"All products",search:"Search products and services...",order:"Order",cart:"Order cart",empty:"Your cart is empty.",sum:"Subtotal",checkout:"Continue checkout",modal:"Place order",qty:"Quantity",target:"Public link / email or username",targetHint:"For social services use a public link. For subscriptions use email or username. Never send a password.",add:"Add to cart",cancel:"Cancel",added:"Added to cart",walletTitle:"Wallet & payments",card:"Card transfer",cardDesc:"Amount → card details → receipt → admin approval → wallet credit",usdt:"USDT",usdtDesc:"Live USDT equivalent → receipt/TXID → admin approval",safe:"Password-free",safeDesc:"Sensitive account passwords are never requested.",results:"results",footer:"Persian Shop — Premium Digital Marketplace"}}

export default function Storefront(){
 const [lang,setLang]=useState<Lang>("fa"),[cat,setCat]=useState<CategoryId|"all">("all"),[q,setQ]=useState(""),[selected,setSelected]=useState<Product|null>(null),[qty,setQty]=useState(1),[target,setTarget]=useState(""),[cart,setCart]=useState<CartLine[]>([]),[drawer,setDrawer]=useState(false),[toast,setToast]=useState(false); const t=text[lang];
 const filtered=useMemo(()=>products.filter(p=>(cat==="all"||p.category===cat)&&(!q||`${p.fa} ${p.en}`.toLowerCase().includes(q.toLowerCase()))),[cat,q]);
 const picks=products.filter(p=>featured.has(p.id)); const total=cart.reduce((s,x)=>s+x.product.price*x.qty,0);
 const open=(p:Product)=>{setSelected(p);setQty(1);setTarget("")};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!selected)return;setCart(v=>[...v,{product:selected,qty,target}]);setSelected(null);setToast(true);setTimeout(()=>setToast(false),1800)};
 const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
 return <main dir={lang==="fa"?"rtl":"ltr"} className="site">
  <header className="topbar"><div className="shell nav"><button className="brand" onClick={()=>scroll("top")}><span className="brandmark">P</span><span>Persian Shop<small>Premium Digital Store</small></span></button><nav><button onClick={()=>scroll("products")}>{t.products}</button><button onClick={()=>scroll("wallet")}>{t.wallet}</button><button onClick={()=>scroll("support")}>{t.support}</button></nav><div className="actions"><button className="lang" onClick={()=>setLang(lang==="fa"?"en":"fa")}>{lang==="fa"?"EN":"فا"}</button><button className="cartbtn" onClick={()=>setDrawer(true)}>🛒 <b>{cart.length}</b></button><button className="account">{t.login}</button></div></div></header>
  <section id="top" className="hero"><div className="orb o1"/><div className="orb o2"/><div className="shell heroGrid"><div><span className="eyebrow">✦ {t.badge}</span><h1>{t.h1}</h1><p>{t.lead}</p><div className="heroBtns"><button className="primary" onClick={()=>scroll("products")}>{t.browse} ←</button><button className="ghost" onClick={()=>scroll("wallet")}>💳 {t.topup}</button></div><div className="stats"><span><b>{products.length}</b>{lang==="fa"?" محصول":" products"}</span><span><b>{categories.length}</b>{lang==="fa"?" دسته‌بندی":" categories"}</span><span><b>24/7</b>{t.support}</span></div></div><div className="heroCard"><div className="shine"/><span className="mini">PERSIAN SHOP</span><h2>Digital Marketplace</h2><p>AI • Social • Premium • Digital</p><div className="floating">⚡ Fast order</div><div className="floating second">🔒 No password</div></div></div></section>
  <section className="shell section"><div className="sectionHead"><div><span className="kicker">01</span><h2>{t.cats}</h2></div></div><div className="catgrid">{categories.map(c=><button key={c.id} style={{"--c":c.color} as CSSProperties} className={`cat ${cat===c.id?"active":""}`} onClick={()=>{setCat(c.id);scroll("products")}}><span className="caticon">{c.emoji}</span><b>{c[lang]}</b><small>{c.desc}</small><i>{products.filter(p=>p.category===c.id).length}</i></button>)}</div></section>
  <section className="shell section featured"><div className="sectionHead"><div><span className="kicker">02</span><h2>{t.featured}</h2></div></div><div className="productgrid featuregrid">{picks.map(p=><ProductCard key={p.id} p={p} lang={lang} onOpen={open}/>)}</div></section>
  <section id="products" className="shell section"><div className="sectionHead productHead"><div><span className="kicker">03</span><h2>{t.all}</h2></div><label className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></label></div><div className="filters"><button className={cat==="all"?"active":""} onClick={()=>setCat("all")}>{t.all}</button>{categories.map(c=><button key={c.id} className={cat===c.id?"active":""} onClick={()=>setCat(c.id)}>{c.emoji} {c[lang]}</button>)}</div><p className="result">{filtered.length} {t.results}</p><div className="productgrid">{filtered.map(p=><ProductCard key={p.id} p={p} lang={lang} onOpen={open}/>)}</div></section>
  <section id="wallet" className="wallet"><div className="shell"><div className="sectionHead"><div><span className="kicker">04</span><h2>{t.walletTitle}</h2></div></div><div className="paygrid"><article><span>💳</span><h3>{t.card}</h3><p>{t.cardDesc}</p><button>{t.topup}</button></article><article><span>₮</span><h3>{t.usdt}</h3><p>{t.usdtDesc}</p><button>{t.topup}</button></article><article id="support"><span>🛡</span><h3>{t.safe}</h3><p>{t.safeDesc}</p><button>{t.support}</button></article></div></div></section>
  <footer><div className="shell"><b>{t.footer}</b><span>© 2026</span></div></footer>
  {selected&&<div className="modalback" onMouseDown={()=>setSelected(null)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={selected[lang]}/><div><span className="eyebrow">{categories.find(c=>c.id===selected.category)?.emoji} {categories.find(c=>c.id===selected.category)?.[lang]}</span><h2>{selected[lang]}</h2><strong>{money(selected.price,lang)}</strong><label>{t.qty}<div className="counter"><button type="button" onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button type="button" onClick={()=>setQty(qty+1)}>+</button></div></label><label>{t.target}<input required value={target} onChange={e=>setTarget(e.target.value)} placeholder={selected.category==="ai"||selected.category==="digital"?"name@example.com":"https://..."}/><small>{t.targetHint}</small></label><div className="total"><span>{t.sum}</span><b>{money(selected.price*qty,lang)}</b></div><div className="modalBtns"><button className="primary" type="submit">{t.add}</button><button className="ghost" type="button" onClick={()=>setSelected(null)}>{t.cancel}</button></div></div></form></div>}
  {drawer&&<><div className="drawerback" onClick={()=>setDrawer(false)}/><aside className="drawer"><div className="drawerHead"><h2>{t.cart}</h2><button onClick={()=>setDrawer(false)}>×</button></div>{!cart.length?<p className="empty">{t.empty}</p>:<div className="cartlines">{cart.map((x,i)=><article key={`${x.product.id}-${i}`}><img src={x.product.image} alt=""/><div><b>{x.product[lang]}</b><small>{x.qty} × {money(x.product.price,lang)}</small></div><button onClick={()=>setCart(v=>v.filter((_,n)=>n!==i))}>×</button></article>)}</div>}<div className="drawerTotal"><span>{t.sum}</span><b>{money(total,lang)}</b></div><button className="primary wide" disabled={!cart.length}>{t.checkout}</button></aside></>}
  {toast&&<div className="toast">✓ {t.added}</div>}
 </main>
}
function ProductCard({p,lang,onOpen}:{p:Product;lang:Lang;onOpen:(p:Product)=>void}){const c=categories.find(x=>x.id===p.category)!;return <article className="product"><div className="picture"><img src={p.image} alt={p[lang]} loading="lazy"/><span>{c.emoji}</span></div><div className="productBody"><small>{c[lang]}</small><h3>{p[lang]}</h3><div><strong>{money(p.price,lang)}</strong><button onClick={()=>onOpen(p)}>{lang==="fa"?"سفارش":"Order"} ←</button></div></div></article>}